# Generated by Django 4.0.5 on 2022-08-17 14:16

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220812_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_url_path, verbose_name='Аватар'),
        ),
    ]
