# Generated by Django 4.0.5 on 2022-08-17 14:26

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.get_url_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg'], 'Файлы только jpg и jpeg')], verbose_name='Аватар'),
        ),
    ]
