# Generated by Django 4.0.5 on 2022-06-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_title1_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('moderated', 'Модерированная'), ('rejected', 'Откланенная')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
