# Generated by Django 4.0.5 on 2022-07-27 14:15

from django.db import migrations, models
import webapp.validate


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_remove_article_tags_old_delete_articletag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, validators=[webapp.validate.validate_title], verbose_name='Заголовок'),
        ),
    ]
