# Generated by Django 4.0.5 on 2022-07-27 14:19

from django.db import migrations
from django.template.defaultfilters import slugify


def fill_slug(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.slug = slugify(article.title)
        article.save()


def rollback_fill(apps, schema_editor):
    Article = apps.get_model('webapp.Article')
    for article in Article.objects.all():
        article.slug = None
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0010_article_slug_alter_article_title'),
    ]

    operations = [
        migrations.RunPython(fill_slug, rollback_fill)
    ]
